package vista;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JDesktopPane;
import vista.interstoks;

public class menu extends javax.swing.JFrame {
    
    public static JDesktopPane jDesktopPane_menu;

    public menu() {
        initComponents();
        this.setSize(new Dimension (1200,700));
        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        this.setTitle("Sistema de Ventas");
        
        this.setLayout(null);
        jDesktopPane_menu = new JDesktopPane();
        
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        this.jDesktopPane_menu.setBounds(0, 0, ancho, (alto - 110));
        this.add(jDesktopPane_menu);
        

   
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1usuario = new javax.swing.JMenu();
        jMenu_nuevo_usuario = new javax.swing.JMenuItem();
        jMenuItem_gest_usuarios = new javax.swing.JMenuItem();
        jMenu_producto = new javax.swing.JMenu();
        jMenuItem_nuevo_produc = new javax.swing.JMenuItem();
        jMenuItem_gest_product = new javax.swing.JMenuItem();
        jMenuItem_act_stpk = new javax.swing.JMenuItem();
        jMenu4_cliente = new javax.swing.JMenu();
        jMenuItem_nuevo_cliente = new javax.swing.JMenuItem();
        jMenuItem_gest_clientes = new javax.swing.JMenuItem();
        jMenu_categoria = new javax.swing.JMenu();
        jMenuItem_nueva_categ = new javax.swing.JMenuItem();
        jMenuItem_gestionar_categ = new javax.swing.JMenuItem();
        jMenu_facturar = new javax.swing.JMenu();
        jMenuItem_nueva_ventas = new javax.swing.JMenuItem();
        jMenuItem_gest_ventas = new javax.swing.JMenuItem();
        jMenu_cerrar_seccion = new javax.swing.JMenu();
        jMenuItem_cerrar_secc = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setFocusable(false);
        setForeground(new java.awt.Color(255, 255, 255));
        setIconImages(null);

        jMenu1usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario-seguro.png"))); // NOI18N
        jMenu1usuario.setText("Usuario");
        jMenu1usuario.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jMenu1usuario.setMaximumSize(new java.awt.Dimension(200, 32767));
        jMenu1usuario.setPreferredSize(new java.awt.Dimension(150, 40));
        jMenu1usuario.setVerifyInputWhenFocusTarget(false);

        jMenu_nuevo_usuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jMenu_nuevo_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo-cliente.png"))); // NOI18N
        jMenu_nuevo_usuario.setText("Nuevo Usuario");
        jMenu_nuevo_usuario.setPreferredSize(new java.awt.Dimension(180, 30));
        jMenu_nuevo_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_nuevo_usuarioActionPerformed(evt);
            }
        });
        jMenu1usuario.add(jMenu_nuevo_usuario);

        jMenuItem_gest_usuarios.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jMenuItem_gest_usuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/configuraciones.png"))); // NOI18N
        jMenuItem_gest_usuarios.setText("Gestionar Usuarios");
        jMenuItem_gest_usuarios.setPreferredSize(new java.awt.Dimension(180, 30));
        jMenuItem_gest_usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_gest_usuariosActionPerformed(evt);
            }
        });
        jMenu1usuario.add(jMenuItem_gest_usuarios);

        jMenuBar1.add(jMenu1usuario);

        jMenu_producto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/producto.png"))); // NOI18N
        jMenu_producto.setText("Producto");
        jMenu_producto.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jMenu_producto.setMaximumSize(new java.awt.Dimension(200, 32767));
        jMenu_producto.setPreferredSize(new java.awt.Dimension(150, 40));
        jMenu_producto.setVerifyInputWhenFocusTarget(false);

        jMenuItem_nuevo_produc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jMenuItem_nuevo_produc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo-producto.png"))); // NOI18N
        jMenuItem_nuevo_produc.setText("Nuevo Producto");
        jMenuItem_nuevo_produc.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenuItem_nuevo_produc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_nuevo_producActionPerformed(evt);
            }
        });
        jMenu_producto.add(jMenuItem_nuevo_produc);

        jMenuItem_gest_product.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jMenuItem_gest_product.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/producto.png"))); // NOI18N
        jMenuItem_gest_product.setText("Gestionar Productos");
        jMenuItem_gest_product.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenuItem_gest_product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_gest_productActionPerformed(evt);
            }
        });
        jMenu_producto.add(jMenuItem_gest_product);

        jMenuItem_act_stpk.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jMenuItem_act_stpk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo.png"))); // NOI18N
        jMenuItem_act_stpk.setText("actualizar Stok");
        jMenuItem_act_stpk.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenuItem_act_stpk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_act_stpkActionPerformed(evt);
            }
        });
        jMenu_producto.add(jMenuItem_act_stpk);

        jMenuBar1.add(jMenu_producto);

        jMenu4_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cliente.png"))); // NOI18N
        jMenu4_cliente.setText("cliente");
        jMenu4_cliente.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jMenu4_cliente.setMaximumSize(new java.awt.Dimension(200, 32767));
        jMenu4_cliente.setPreferredSize(new java.awt.Dimension(150, 40));
        jMenu4_cliente.setVerifyInputWhenFocusTarget(false);

        jMenuItem_nuevo_cliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jMenuItem_nuevo_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo-cliente.png"))); // NOI18N
        jMenuItem_nuevo_cliente.setText("Nuevo Cliente");
        jMenuItem_nuevo_cliente.setPreferredSize(new java.awt.Dimension(180, 30));
        jMenuItem_nuevo_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_nuevo_clienteActionPerformed(evt);
            }
        });
        jMenu4_cliente.add(jMenuItem_nuevo_cliente);

        jMenuItem_gest_clientes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jMenuItem_gest_clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cliente.png"))); // NOI18N
        jMenuItem_gest_clientes.setText("Gestionar Cliente");
        jMenuItem_gest_clientes.setPreferredSize(new java.awt.Dimension(180, 30));
        jMenuItem_gest_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_gest_clientesActionPerformed(evt);
            }
        });
        jMenu4_cliente.add(jMenuItem_gest_clientes);

        jMenuBar1.add(jMenu4_cliente);

        jMenu_categoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/categorias.png"))); // NOI18N
        jMenu_categoria.setText("categoria");
        jMenu_categoria.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jMenu_categoria.setMaximumSize(new java.awt.Dimension(200, 32767));
        jMenu_categoria.setPreferredSize(new java.awt.Dimension(150, 40));
        jMenu_categoria.setVerifyInputWhenFocusTarget(false);

        jMenuItem_nueva_categ.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jMenuItem_nueva_categ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo.png"))); // NOI18N
        jMenuItem_nueva_categ.setText("Nueva categoria");
        jMenuItem_nueva_categ.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenuItem_nueva_categ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_nueva_categActionPerformed(evt);
            }
        });
        jMenu_categoria.add(jMenuItem_nueva_categ);

        jMenuItem_gestionar_categ.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jMenuItem_gestionar_categ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/categorias.png"))); // NOI18N
        jMenuItem_gestionar_categ.setText("gestionar Categoria");
        jMenuItem_gestionar_categ.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenuItem_gestionar_categ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_gestionar_categActionPerformed(evt);
            }
        });
        jMenu_categoria.add(jMenuItem_gestionar_categ);

        jMenuBar1.add(jMenu_categoria);

        jMenu_facturar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carrito.png"))); // NOI18N
        jMenu_facturar.setText("Facturar");
        jMenu_facturar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jMenu_facturar.setMaximumSize(new java.awt.Dimension(200, 32767));
        jMenu_facturar.setPreferredSize(new java.awt.Dimension(150, 40));
        jMenu_facturar.setVerifyInputWhenFocusTarget(false);

        jMenuItem_nueva_ventas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jMenuItem_nueva_ventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/anadir.png"))); // NOI18N
        jMenuItem_nueva_ventas.setText("Nueva Venta");
        jMenuItem_nueva_ventas.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenuItem_nueva_ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_nueva_ventasActionPerformed(evt);
            }
        });
        jMenu_facturar.add(jMenuItem_nueva_ventas);

        jMenuItem_gest_ventas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jMenuItem_gest_ventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/configuraciones.png"))); // NOI18N
        jMenuItem_gest_ventas.setText("Gestinar Ventas");
        jMenuItem_gest_ventas.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenuItem_gest_ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_gest_ventasActionPerformed(evt);
            }
        });
        jMenu_facturar.add(jMenuItem_gest_ventas);

        jMenuBar1.add(jMenu_facturar);

        jMenu_cerrar_seccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar-sesion.png"))); // NOI18N
        jMenu_cerrar_seccion.setText("Cerrar seccion");
        jMenu_cerrar_seccion.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jMenu_cerrar_seccion.setMaximumSize(new java.awt.Dimension(200, 32767));
        jMenu_cerrar_seccion.setPreferredSize(new java.awt.Dimension(150, 40));
        jMenu_cerrar_seccion.setVerifyInputWhenFocusTarget(false);

        jMenuItem_cerrar_secc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jMenuItem_cerrar_secc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar-sesion.png"))); // NOI18N
        jMenuItem_cerrar_secc.setText("Cerrar Seccion");
        jMenuItem_cerrar_secc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_cerrar_seccActionPerformed(evt);
            }
        });
        jMenu_cerrar_seccion.add(jMenuItem_cerrar_secc);

        jMenuBar1.add(jMenu_cerrar_seccion);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu_nuevo_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_nuevo_usuarioActionPerformed
   inter_usuario acrualizarstoc = new inter_usuario();
    jDesktopPane_menu.add(acrualizarstoc);
    acrualizarstoc.setVisible(true);  
    }//GEN-LAST:event_jMenu_nuevo_usuarioActionPerformed

    private void jMenuItem_act_stpkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_act_stpkActionPerformed
        
        interstoks acrualizarstock = new interstoks();
        jDesktopPane_menu.add(acrualizarstock);
        acrualizarstock.setVisible(true); 
    }//GEN-LAST:event_jMenuItem_act_stpkActionPerformed

    private void jMenuItem_gest_ventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_gest_ventasActionPerformed
      intergestionar_ventas int_categoria = new intergestionar_ventas();
        jDesktopPane_menu.add(int_categoria);
        int_categoria.setVisible(true);  

    }//GEN-LAST:event_jMenuItem_gest_ventasActionPerformed

    private void jMenuItem_nueva_categActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_nueva_categActionPerformed
        int_categoria int_categoria = new int_categoria();
        jDesktopPane_menu.add(int_categoria);
        int_categoria.setVisible(true);
    }//GEN-LAST:event_jMenuItem_nueva_categActionPerformed

    private void jMenuItem_gestionar_categActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_gestionar_categActionPerformed
        intergestionar_categorias Intergestionar_categorias = new intergestionar_categorias();        
        jDesktopPane_menu.add(Intergestionar_categorias);
        Intergestionar_categorias.setVisible(true);
    }//GEN-LAST:event_jMenuItem_gestionar_categActionPerformed

    private void jMenuItem_nuevo_producActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_nuevo_producActionPerformed
            inter_producto vistanuevoproducto = new inter_producto();        
        jDesktopPane_menu.add(vistanuevoproducto);
       vistanuevoproducto.setVisible(true);
    }//GEN-LAST:event_jMenuItem_nuevo_producActionPerformed

    private void jMenuItem_gest_productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_gest_productActionPerformed
         intergestionar_producto intercategoria = new intergestionar_producto();        
        jDesktopPane_menu.add(intercategoria );
       intercategoria.setVisible(true);
        System.out.println(" gestionar categorias abierto");
    }//GEN-LAST:event_jMenuItem_gest_productActionPerformed

    private void jMenuItem_nuevo_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_nuevo_clienteActionPerformed
       inter_cliente intercliente = new inter_cliente();        
        jDesktopPane_menu.add(intercliente);
       intercliente.setVisible(true);
    }//GEN-LAST:event_jMenuItem_nuevo_clienteActionPerformed

    private void jMenuItem_gest_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_gest_clientesActionPerformed

intergestionar_cliente intergestcliente = new intergestionar_cliente();        
        jDesktopPane_menu.add(intergestcliente);
       intergestcliente.setVisible(true);
    }//GEN-LAST:event_jMenuItem_gest_clientesActionPerformed

    private void jMenuItem_gest_usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_gest_usuariosActionPerformed
intergestionar_usuarios intergestcliente = new intergestionar_usuarios();        
        jDesktopPane_menu.add(intergestcliente);
       intergestcliente.setVisible(true);

    }//GEN-LAST:event_jMenuItem_gest_usuariosActionPerformed

    private void jMenuItem_nueva_ventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_nueva_ventasActionPerformed
        inter_facturacion intergestcliente = new inter_facturacion();        
        jDesktopPane_menu.add(intergestcliente);
       intergestcliente.setVisible(true);
    }//GEN-LAST:event_jMenuItem_nueva_ventasActionPerformed

    private void jMenuItem_cerrar_seccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_cerrar_seccActionPerformed
       login log = new login();        
       log.setVisible(true); 
       this.dispose();
    }//GEN-LAST:event_jMenuItem_cerrar_seccActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1usuario;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4_cliente;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem_act_stpk;
    private javax.swing.JMenuItem jMenuItem_cerrar_secc;
    private javax.swing.JMenuItem jMenuItem_gest_clientes;
    private javax.swing.JMenuItem jMenuItem_gest_product;
    private javax.swing.JMenuItem jMenuItem_gest_usuarios;
    private javax.swing.JMenuItem jMenuItem_gest_ventas;
    private javax.swing.JMenuItem jMenuItem_gestionar_categ;
    private javax.swing.JMenuItem jMenuItem_nueva_categ;
    private javax.swing.JMenuItem jMenuItem_nueva_ventas;
    private javax.swing.JMenuItem jMenuItem_nuevo_cliente;
    private javax.swing.JMenuItem jMenuItem_nuevo_produc;
    private javax.swing.JMenu jMenu_categoria;
    private javax.swing.JMenu jMenu_cerrar_seccion;
    private javax.swing.JMenu jMenu_facturar;
    private javax.swing.JMenuItem jMenu_nuevo_usuario;
    private javax.swing.JMenu jMenu_producto;
    private javax.swing.JPopupMenu jPopupMenu1;
    // End of variables declaration//GEN-END:variables
}
